#' NCL Theme Palettes
#'
#' This function returns a palette generated by colorRampPalette from one of the
#' NCL palettes
#'
#' @param palette The name of palette to use
#' @param reverse Optional: boolean value to reverse the palette
#' @param ... arguments to pass to colorRamp
#'
#' @return A colorRamp function
#' @export
#'
#' @examples
#' ncl_theme_pal()
#' # or, specify a paltte
#' ncl_theme_pal("ics")
#' # a reverse palette
#' ncl_theme_pal("icb", TRUE)
ncl_theme_pal <- function(palette = c(
                          "ics",
                          "icb",
                          "icb_darkblue",
                          "icb_brightblue",
                          "icb_aquablue",
                          "icb_lightblue",
                          "icb_nhsblue",
                          "icb_darkgrey",
                          "icb_midgrey",
                          "ics_purple",
                          "ics_pink",
                          "ics_limegreen",
                          "ics_brightgreen",
                          "ics_teal"
                         ),
                         reverse = FALSE,
                         ...) {
  palette <- match.arg(palette)

  pal <- ncl_theme_cols(palette = palette)

  if (reverse) pal <- rev(pal)

  grDevices::colorRampPalette(pal, ...)
}
